### ISSUE TITLE
Nuget Packages Issue with Demos

### ISSUE THREAD

**Issue by drcrook1** [mbraceproject/MBrace.Demos#4]
MBraceAzureClient does not have nugget package definitions for the packages it is attempting to bring in and use.  This makes the demos not work on a box that does not have these already located in the appropriate folders.

**Comment by krontogiannis** [comment]
Thanks. There seems to be an issue with VS package manager; MBrace.Azure.Client package was downloaded but wasn't added in packages.config (might have to do with the fact that this package does not have a lib folder or sth).

Fixed in 95e12d06ba7c6b7d859b0d7384747cef6814e278
